# Use an official Node.js runtime as a base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /fem

# Copy package.json and package-lock.json (if available) into the container
COPY client/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the React app source code
COPY client /fem

# Build the React app for production
RUN npm run build

# Expose the port React will serve the app from (default: 3000)
EXPOSE 3000

# Serve the static build with a static server (using npm's `serve`)
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
